"""Samples slice: enumerate the labeled documents shipped with / generated by the repo."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from src.schemas import SuretySubmission
from web.api.config import REPO_ROOT

CASES = REPO_ROOT / "evals" / "cases"
VAL = REPO_ROOT / "data" / "synthetic" / "val"


@dataclass
class Sample:
    id: str
    path: Path
    ground_truth_path: Path | None


def _scan() -> dict[str, Sample]:
    samples: dict[str, Sample] = {}
    for d, prefix in ((CASES, "cases"), (VAL, "val")):
        if not d.exists():
            continue
        for txt in sorted(d.glob("*.txt")):
            gt = txt.with_suffix(".json")
            sid = f"{prefix}/{txt.stem}"
            samples[sid] = Sample(id=sid, path=txt, ground_truth_path=gt if gt.exists() else None)
    return samples


def list_samples() -> list[dict]:
    out = []
    for s in _scan().values():
        text = s.path.read_text()
        # First subject-ish line as a title, else the first non-empty line.
        title = next((l.removeprefix("Subject:").strip() for l in text.splitlines() if l.startswith("Subject:")), None)
        title = title or next((l.strip() for l in text.splitlines() if l.strip()), s.id)
        out.append(
            {
                "id": s.id,
                "title": title[:90],
                "preview": text[:220],
                "has_ground_truth": s.ground_truth_path is not None,
            }
        )
    return out


def get_sample(sample_id: str) -> dict | None:
    s = _scan().get(sample_id)
    if not s:
        return None
    gt = None
    if s.ground_truth_path:
        gt = SuretySubmission.model_validate_json(s.ground_truth_path.read_text()).model_dump()
    return {"id": s.id, "text": s.path.read_text(), "ground_truth": gt}


def get_ground_truth(sample_id: str) -> SuretySubmission | None:
    s = _scan().get(sample_id)
    if not s or not s.ground_truth_path:
        return None
    return SuretySubmission.model_validate_json(s.ground_truth_path.read_text())
