/** Mock source configs for the integration-map demo.
 *  Grounded in research (docs/RLI-data-sources-research.md): provenance tags are
 *  honest — "confirmed" = public RLI source, "industry-standard" = canonical
 *  surety practice (SBA/FCRA/vendor docs), "inferred" = reasonable assumption.
 *  No real connectors exist; this view is design-partner material. */

export type Provenance = "confirmed" | "industry-standard" | "inferred";
export type Connection = "webhook" | "api-poll" | "sftp" | "on-demand";
export type Health = "live" | "scheduled" | "degraded";
export type Tier = "FirstStep" | "Next Step" | "Standard" | "SBA Capacity";

export type SourceConfig = {
  id: string;
  name: string;
  category: "submission" | "carrier" | "enrichment";
  systemNote: string;
  provenance: Provenance;
  connection: Connection;
  cadence: string;
  cadenceRationale: string;
  direction: "read" | "read-write";
  piiClass: "none" | "business" | "high";
  health: Health;
  lastSyncMinsAgo: number;
  volumePerDay: string;
  feeds: string[];
  tiers: Tier[];
  compliance?: string;
};

export const TIERS: Tier[] = ["FirstStep", "Next Step", "Standard", "SBA Capacity"];

export const SOURCES: SourceConfig[] = [
  // ---- Submission channels ----
  {
    id: "email-inbox",
    name: "Agent submission inbox",
    category: "submission",
    systemNote: "CPA financial packages + Excel WIP schedules arrive as email attachments — the Standard-tier reality",
    provenance: "industry-standard",
    connection: "webhook",
    cadence: "real-time",
    cadenceRationale: "Inbound mail webhook; documents queue for extraction within seconds of arrival.",
    direction: "read",
    piiClass: "high",
    health: "live",
    lastSyncMinsAgo: 2,
    volumePerDay: "~140 docs",
    feeds: ["principal", "financials (working_capital, net_worth)", "wip_schedule", "bond details"],
    tiers: ["Standard", "SBA Capacity"],
    compliance: "Attachments contain NPI — PII classification runs before tracing or storage.",
  },
  {
    id: "contract-bond-app",
    name: "My Contract Bond App",
    category: "submission",
    systemNote: "RLI's contract-surety intake: prequal/bid/P&P applications, e-signed GIAs, KBA-verified indemnitors, doc upload",
    provenance: "confirmed",
    connection: "webhook",
    cadence: "real-time",
    cadenceRationale: "Application-submitted events push structured fields + uploaded contract documents.",
    direction: "read",
    piiClass: "high",
    health: "live",
    lastSyncMinsAgo: 11,
    volumePerDay: "~60 apps",
    feeds: ["principal", "obligee", "bond_type", "bond_amount", "GIA execution status"],
    tiers: ["FirstStep", "Next Step", "Standard"],
  },
  {
    id: "rlink",
    name: "RLink / MyBondApp",
    category: "submission",
    systemNote: "Transactional commercial surety platform — automated underwriting, rating, straight-through issuance",
    provenance: "confirmed",
    connection: "api-poll",
    cadence: "real-time",
    cadenceRationale: "Transactional bonds are largely straight-through; this pipeline sees referrals and exceptions.",
    direction: "read",
    piiClass: "business",
    health: "live",
    lastSyncMinsAgo: 6,
    volumePerDay: "~220 bonds",
    feeds: ["bond_type (license_permit, court, fidelity, notary)", "principal", "referral reasons"],
    tiers: ["FirstStep"],
  },
  {
    id: "broker-sftp",
    name: "Broker SFTP drop",
    category: "submission",
    systemNote: "Nightly batch packages from high-volume brokerages",
    provenance: "inferred",
    connection: "sftp",
    cadence: "nightly",
    cadenceRationale: "Large brokers batch-export; nightly matches their AMS export schedules.",
    direction: "read",
    piiClass: "high",
    health: "degraded",
    lastSyncMinsAgo: 26 * 60,
    volumePerDay: "~38 docs",
    feeds: ["full submission packages"],
    tiers: ["Standard"],
    compliance: "Last drop 26h ago — expected every 24h. Alert raised to the broker's ops contact.",
  },
  // ---- Carrier systems ----
  {
    id: "bond-sor",
    name: "Bond system of record",
    category: "carrier",
    systemNote: "Clearance & dedup lookups: has this principal or bond been seen before? (PAS vendor not public)",
    provenance: "inferred",
    connection: "api-poll",
    cadence: "15 min",
    cadenceRationale: "Clearance checks must be near-fresh; 15-minute polling balances load on the core system.",
    direction: "read",
    piiClass: "business",
    health: "live",
    lastSyncMinsAgo: 9,
    volumePerDay: "~800 lookups",
    feeds: ["clearance/dedup step", "prior bond history", "renewal linkage"],
    tiers: ["FirstStep", "Next Step", "Standard", "SBA Capacity"],
  },
  {
    id: "ams-feeds",
    name: "AMS agency feeds",
    category: "carrier",
    systemNote: "Applied Epic / AMS360 / HawkSoft downloads — confirmed on RLI's P&C side (QuickWrite), extended here to surety",
    provenance: "inferred",
    connection: "api-poll",
    cadence: "hourly",
    cadenceRationale: "Agency records change slowly; hourly sync keeps producer + client records aligned.",
    direction: "read",
    piiClass: "business",
    health: "scheduled",
    lastSyncMinsAgo: 41,
    volumePerDay: "~1.2k records",
    feeds: ["agent/agency attribution", "client master records"],
    tiers: ["Next Step", "Standard"],
  },
  {
    id: "dms",
    name: "Document management",
    category: "carrier",
    systemNote: "Extractions and issued bond documents written back as the system-of-record copy",
    provenance: "inferred",
    connection: "api-poll",
    cadence: "on completion",
    cadenceRationale: "Write-back happens at pipeline completion; every stored doc carries its extraction lineage.",
    direction: "read-write",
    piiClass: "high",
    health: "live",
    lastSyncMinsAgo: 4,
    volumePerDay: "~300 writes",
    feeds: ["audit trail", "document lineage", "issued bonds"],
    tiers: ["FirstStep", "Next Step", "Standard", "SBA Capacity"],
  },
  // ---- External enrichment ----
  {
    id: "dnb",
    name: "D&B business credit + legal events",
    category: "enrichment",
    systemNote: "Business credit, liens, judgments, bankruptcies, UCC filings — pulled per submission + nightly portfolio monitor",
    provenance: "industry-standard",
    connection: "on-demand",
    cadence: "per submission + nightly monitor",
    cadenceRationale: "Fresh pull at underwriting time; nightly monitoring flags new legal events on active principals.",
    direction: "read",
    piiClass: "business",
    health: "live",
    lastSyncMinsAgo: 18,
    volumePerDay: "~90 pulls",
    feeds: ["appetite/triage score", "legal-event flags", "credit signals"],
    tiers: ["Next Step", "Standard", "SBA Capacity"],
    compliance: "External subprocessor — DPA + SOC 2 report on the vendor register.",
  },
  {
    id: "personal-credit",
    name: "Owner personal credit",
    category: "enrichment",
    systemNote: "Bureau soft pull on owners/indemnitors for fast-track programs — FCRA consent-gated",
    provenance: "industry-standard",
    connection: "on-demand",
    cadence: "per application",
    cadenceRationale: "Pulled only with the applicant's written FCRA authorization from the bond application.",
    direction: "read",
    piiClass: "high",
    health: "live",
    lastSyncMinsAgo: 33,
    volumePerDay: "~45 pulls",
    feeds: ["fast-track eligibility", "indemnitor risk"],
    tiers: ["FirstStep", "Next Step"],
    compliance: "FCRA-regulated: consent required; adverse-action notice workflow on declines.",
  },
  {
    id: "lexis",
    name: "LexisNexis public records",
    category: "enrichment",
    systemNote: "Entity linkage + derogatory-event research across public records",
    provenance: "industry-standard",
    connection: "on-demand",
    cadence: "per submission",
    cadenceRationale: "Investigative due diligence at underwriting time.",
    direction: "read",
    piiClass: "high",
    health: "live",
    lastSyncMinsAgo: 52,
    volumePerDay: "~30 queries",
    feeds: ["entity resolution", "public-record flags"],
    tiers: ["Standard", "SBA Capacity"],
    compliance: "Non-FCRA product: cannot be the sole basis for an eligibility decision — verification required.",
  },
  {
    id: "sos-ucc",
    name: "State SoS · UCC search",
    category: "enrichment",
    systemNote: "Secretary of State UCC filing searches — who holds security interests in the principal's assets",
    provenance: "industry-standard",
    connection: "on-demand",
    cadence: "per submission",
    cadenceRationale: "UCC positions matter at decision time; no monitoring needed between submissions.",
    direction: "read",
    piiClass: "business",
    health: "live",
    lastSyncMinsAgo: 75,
    volumePerDay: "~25 searches",
    feeds: ["secured-creditor picture", "collateral flags"],
    tiers: ["Standard", "SBA Capacity"],
  },
  {
    id: "pacer",
    name: "PACER federal courts",
    category: "enrichment",
    systemNote: "Federal civil litigation + bankruptcy sweep on active principals",
    provenance: "industry-standard",
    connection: "api-poll",
    cadence: "weekly",
    cadenceRationale: "Bankruptcy filings are rare but decisive; a weekly portfolio sweep catches them early.",
    direction: "read",
    piiClass: "business",
    health: "scheduled",
    lastSyncMinsAgo: 2 * 24 * 60,
    volumePerDay: "weekly sweep",
    feeds: ["bankruptcy flags", "litigation history"],
    tiers: ["Standard", "SBA Capacity"],
  },
  {
    id: "sba",
    name: "SBA bond guarantee program",
    category: "enrichment",
    systemNote: "Forms 994/994F, XBRL WIP schedules — the SBA Capacity program's guarantee workflow",
    provenance: "industry-standard",
    connection: "on-demand",
    cadence: "per guaranteed bond",
    cadenceRationale: "Guarantee applications follow SBA SOP; WIP arrives as computer-readable spreadsheet (XBRL).",
    direction: "read-write",
    piiClass: "high",
    health: "scheduled",
    lastSyncMinsAgo: 6 * 60,
    volumePerDay: "~8 filings",
    feeds: ["wip_schedule (994F)", "guarantee status"],
    tiers: ["SBA Capacity"],
  },
  {
    id: "sam-gov",
    name: "SAM.gov / public bid data",
    category: "enrichment",
    systemNote: "Federal awards + public bid tabs to verify claimed project history",
    provenance: "industry-standard",
    connection: "api-poll",
    cadence: "monthly",
    cadenceRationale: "Project-history verification is corroborative, not time-critical.",
    direction: "read",
    piiClass: "none",
    health: "scheduled",
    lastSyncMinsAgo: 9 * 24 * 60,
    volumePerDay: "monthly sweep",
    feeds: ["completed-project verification", "obligee history"],
    tiers: ["Standard", "SBA Capacity"],
  },
];

export const CATEGORY_LABELS: Record<SourceConfig["category"], string> = {
  submission: "Submission channels",
  carrier: "Carrier systems",
  enrichment: "External enrichment",
};

export const RECENT_ACTIVITY: { minsAgo: number; source: string; sourceId: string; event: string }[] = [
  { minsAgo: 2, source: "Agent inbox", sourceId: "email-inbox", event: "3 attachments queued — CPA package, Riverbend Grading" },
  { minsAgo: 6, source: "RLink", sourceId: "rlink", event: "2 referrals routed to underwriting review" },
  { minsAgo: 11, source: "My Contract Bond App", sourceId: "contract-bond-app", event: "eGIA executed — 3 indemnitors KBA-verified" },
  { minsAgo: 18, source: "D&B monitor", sourceId: "dnb", event: "2 new liens flagged on active principals" },
  { minsAgo: 33, source: "Personal credit", sourceId: "personal-credit", event: "soft pull complete — FirstStep applicant" },
  { minsAgo: 41, source: "AMS feed", sourceId: "ams-feeds", event: "1,184 agency records reconciled" },
  { minsAgo: 75, source: "SoS UCC", sourceId: "sos-ucc", event: "4 secured filings found — Pine Ridge Sitework" },
  { minsAgo: 26 * 60, source: "Broker SFTP", sourceId: "broker-sftp", event: "⚠ expected drop missed — broker ops notified" },
];
